### ISSUE TITLE
ignoreArrayOrder: true + referenceProperty set should make superdiff disregard changes of position in arrays

### ISSUE THREAD

**Issue by martinjo** [DoneDeal0/superdiff#22]
I was hoping to get this case to work:

describe('JSON Diff with Superdiff', () => {
  const options = { referenceProperty: 'id', ignoreArrayOrder: false };

  it('should ignore position changes in arrays', () => {
    const original = [{ id: 1, name: 'Alice' }, { id: 2, name: 'Bob' }];
    const updated = [{ id: 2, name: 'Bob' }, { id: 1, name: 'Alice' }];

    const diff = getObjectDiff(original, updated, options);
    expect(diff.status).toBe('equal');
  });

But instead it will list both array items as updated. Is there a way to make superdiff disregard changes of items position in an array completely?

**Comment by DoneDeal0** [comment]
Hi @martinjo , 

It's easy to add. I'll add some tests in the week and publish a release asap.

**Comment by martinjo** [comment]
Oh, nice! 

Thanks! 🙏

**Comment by DoneDeal0** [comment]
The option has been added and the library has been updated on npm. Let me know if it works for you!

If your company uses the project for commercial purposes, feel free to [support it](https://github.com/sponsors/DoneDeal0).

Have a great day!

[Release note](https://github.com/DoneDeal0/superdiff/releases/tag/v1.1.3).
