### ISSUE TITLE
[Feature request] Allow filtering of statuses 

### ISSUE THREAD

**Issue by omonk** [DoneDeal0/superdiff#9]
When dealing with large objects it would be very handy to be able to pass an array of statuses to filter out those you're not interested in.

```typescript
type Options = {
    discardArrayOrder?: boolean;
    statuses: DiffStatus[]
};
```

```javascript
const diff = getObjectDiff(
   audience,
   newAudience,
   { statuses: ["updated"] }
);
```

**Comment by DoneDeal0** [comment]
Hi @omonk, thanks for the feature request! It sounds great, I'll implement it when I have some free time.

**Comment by DoneDeal0** [comment]
It's done. Please see the [release note](https://github.com/DoneDeal0/superdiff/releases/tag/v1.0.9) or the documentation for more details. If you need any help, or have any remarks about this new feature please let me know.

You now have complete control over your output (object and list). You can either focus on the main properties only or check their subproperties as well. I hope this meets your expectations.

**Comment by omonk** [comment]
@DoneDeal0 - I never thanked you for such a quick turn around time! So, thank you!

**Comment by DoneDeal0** [comment]
No problem, thank you so much for the coffee, I highly appreciate it!
